apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: agent-nmstate
  namespace: agent
  labels:
    nmstate-label: agent
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        mac-address: 52:54:00:e0:3c:77
        ipv4:
          enabled: true
          address:
            - ip: 192.168.50.20
              prefix-length: 24
          dhcp: false
    dns-resolver:
      config:
        server:
          - 192.168.50.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.50.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - name: "enp1s0"
      macAddress: "52:54:00:e0:3c:77"
